FROM maven:3.8.3-openjdk-11 AS builder

WORKDIR /app

COPY pom.xml .

RUN mvn dependency:go-offline

COPY . .

RUN mvn package -DskipTests

FROM openjdk:11-jre-slim

WORKDIR /app

COPY --from=builder /app/target/seu-arquivo.jar /app/seu-arquivo.jar

EXPOSE 8080

CMD ["java", "-jar", "seu-arquivo.jar"]
